# Generated by Django 5.0.1 on 2024-01-14 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('is_origin', models.BooleanField(default=False)),
                ('path', models.FileField(blank=True, null=True, upload_to='lectures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'ppt', 'txt'])])),
            ],
        ),
    ]
