# Generated by Django 5.0.1 on 2024-01-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
