# Generated by Django 5.0.1 on 2024-01-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_lecture_thumbnail_url'),
        ('login', '0003_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_path', models.CharField(max_length=255)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='LectureVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.PositiveIntegerField()),
                ('video_url', models.URLField(max_length=1024)),
                ('video_title', models.CharField(max_length=255)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='lecture.lecture')),
            ],
            options={
                'unique_together': {('lecture', 'video_id')},
            },
        ),
    ]
